# Generated by Django 3.2.4 on 2021-06-30 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='paciente',
            fields=[
                ('id_registro', models.AutoField(primary_key=True, serialize=False)),
                ('rut_paciente', models.CharField(max_length=12)),
                ('dni_extranjero', models.CharField(max_length=9)),
                ('nombres', models.CharField(max_length=40)),
                ('apellidos', models.CharField(max_length=40)),
                ('fecha_nac', models.DateField(verbose_name='Fecha de nacimiento: Ejemplo 05/05/1995')),
                ('direccion', models.CharField(max_length=30, verbose_name='Dirección')),
                ('num_casa', models.CharField(max_length=10, verbose_name='Número de casa')),
                ('telefono', models.CharField(max_length=9, verbose_name='Teléfono')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
            ],
        ),
    ]
