# Generated by Django 3.2.4 on 2021-06-07 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='fecha_nac',
            field=models.DateField(verbose_name='Fecha de nacimiento: Ejemplo 05/05/1995'),
        ),
    ]
