# Generated by Django 3.2.4 on 2021-06-07 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='profesionale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut_profesional', models.CharField(max_length=12)),
                ('nombres', models.CharField(max_length=150, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=150, verbose_name='Apellidos')),
                ('fecha_nac', models.DateField(verbose_name='Fecha de nacimiento: Ejemplo 04/03/1996')),
                ('direccion', models.CharField(max_length=100, verbose_name='Dirección')),
                ('num_casa', models.CharField(max_length=6, verbose_name='Número de casa')),
                ('telefono', models.CharField(max_length=9, verbose_name='Teléfono')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('profesion', models.CharField(choices=[('0', 'Profesión 1'), ('1', 'Profesión 2'), ('2', 'Profesión 3'), ('3', 'Profesión 4')], default=None, max_length=11, null=True)),
            ],
        ),
    ]
