# Generated by Django 3.2.4 on 2021-07-08 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesionales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesionale',
            name='profesion',
            field=models.CharField(choices=[('Kinesíologo', 'Kinesíologo'), ('Técnico en Enfermería', 'Técnico en Enfermería'), ('Otro', 'Otro')], default=None, max_length=25, null=True),
        ),
    ]
