# Generated by Django 3.2.4 on 2021-06-07 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesionales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesionale',
            name='profesion',
            field=models.CharField(choices=[('0', 'Kinesiologo'), ('1', 'Enfermera'), ('2', 'Tens'), ('3', 'Profesión 4')], default=None, max_length=11, null=True),
        ),
    ]
